# Generated by Django 2.2 on 2020-09-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['is_active']},
        ),
        migrations.AlterModelTable(
            name='site',
            table='sites',
        ),
    ]
