# Generated by Django 2.2 on 2020-09-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites_list', '0002_auto_20200920_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['-is_active']},
        ),
    ]
