# Generated by Django 2.2 on 2020-09-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites_list', '0003_auto_20200920_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='site',
            new_name='site_url',
        ),
    ]
