# Generated by Django 2.2 on 2020-09-27 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites_list', '0004_auto_20200927_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateField()),
                ('status_code', models.CharField(max_length=300)),
                ('the_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites_list.Site')),
            ],
            options={
                'ordering': ['date_and_time'],
            },
        ),
    ]
