# Generated by Django 2.2 on 2020-09-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_list', '0005_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date_and_time',
            field=models.DateTimeField(),
        ),
    ]
