# Generated by Django 2.2 on 2020-09-27 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sites_list', '0006_auto_20200927_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='log',
            name='date_and_time',
        ),
        migrations.AddField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
