# Generated by Django 2.2 on 2020-09-27 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites_list', '0007_auto_20200927_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['the_site']},
        ),
    ]
