# Generated by Django 2.2 on 2020-10-01 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_list', '0011_auto_20200930_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='responsible_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
